//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EthnicEntities1 : DbContext
    {
        public EthnicEntities1()
            : base("name=EthnicEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblBooking> tblBookings { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblImageUpload> tblImageUploads { get; set; }
        public virtual DbSet<tblProductManagement> tblProductManagements { get; set; }
        public virtual DbSet<tblSliderImage> tblSliderImages { get; set; }
        public virtual DbSet<tblSubCategory> tblSubCategories { get; set; }
    }
}
