//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategory
    {
        public tblCategory()
        {
            this.tblProductManagements = new HashSet<tblProductManagement>();
            this.tblSubCategories = new HashSet<tblSubCategory>();
        }
    
        public int id { get; set; }
        public string category_name { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual ICollection<tblProductManagement> tblProductManagements { get; set; }
        public virtual ICollection<tblSubCategory> tblSubCategories { get; set; }
    }
}
