//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductManagement
    {
        public int id { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<int> subcategoryid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string features { get; set; }
        public string price { get; set; }
        public string quality { get; set; }
        public string code { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
