//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubCategory
    {
        public tblSubCategory()
        {
            this.tblProductManagements = new HashSet<tblProductManagement>();
        }
    
        public int id { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string subcategory { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual ICollection<tblProductManagement> tblProductManagements { get; set; }
    }
}
